# Generated by Django 4.1.7 on 2023-04-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
